### ISSUE TITLE
Phonon Roadmap

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-network#14]
This document is intended to provide a high level overview of the development tasks included in the development of the phonon network which can serve as a basis for planning.

### Card Specification
The phonon card applet provides the foundation of the phonon network system, by providing hardware enforced secure storage of 'phonons' themselves, the private keys which grant access to each phonon's corresponding blockchain cryptoassets. 

The commands that the card needs to support for the spec to work are given in detail within the card specification: https://github.com/GridPlus/phonon-network/blob/master/card-specification.md#31-command-table

Currently the spec has a near complete list of the commands but few of them have defined schemas for command and response. Some additional commands for card initialization and provisioning will likely need to be added. 

##### Card Spec Tasks

- [x] Define and document command and response schemas for each command
- [x] Implement phonon javacard applet to handle each command on the card
- [x] Implement golang card interface to send each command and interpret each response
- [ ] Define supported deployment targets and implement transfer backends for them (HID Reader, Lattice1/Mailbox, remote terminal, etc.) 

### Phonon Client Logic
The high level operations of phonon must be defined and implemented. For the most part these are described in detail in the phonon network spec: https://github.com/GridPlus/phonon-network#1-network-overview

These are things like creating phonons, transferring phonons, and redeeming phonons, as well as all of the logic involved in these operations, such as validating phonons, viewing balances, etc.

##### Phonon Client Tasks

- [ ] Define complete set of user facing phonon operations (view balance, deposit, withdraw, etc.)
- [ ] Implement each action against card and blockchain interfaces

### Phonon Terminal 
The phonon client logic needs to handle connections to various card transfer backends, potentially concurrently, and handle potentially long running sessions from clients

- [ ] Define logic for handling card sessions
- [ ] Ensure operations touching multiple cards are directed to the correct sessions

### Phonon Blockchain Interface 
The phonon client must interact with blockchains in order to create and redeem the phonons which can then transact within the phonon network

##### Phonon Blockchain tasks

- [ ] Select and define supported assets
- [ ] Define blockchain interface that can be implemented for multiple blockchain backends
- [ ] Implement basic phonon functions for at least one blockchain backend

### User Interface
Users need some way to interact with the phonon client in order to use the phonon network. A user interface must be provided that makes it convenient for people to do so. 

- [ ] Define user interface (webapp, lattice UI, CLI, etc.)
- [ ] Implement at least one interface

## Proposed Roadmap
Since we have a javacard contractor currently working on the phonon javacard applet, it makes sense to define and implement the majority of the card spec first. Fortunately this is also the most well defined part of the existing spec. The golang side of these commands should ultimately 

Concurrently, it would be good to implement a thin slice through the phonon network design, by implementing a single piece of phonon functionality end to end. A good candidate would be `Create Phonon`. This will allow us to validate that the design will function as defined, flush out any bad assumptions, and allow us to make changes to the card spec before it has been implemented in it's entirety. 

This thin slice should proceed from implementing the card commands, to implementing the client and terminal logic, to implementing the blockchain requests necessary to create phonons. A simple CLI UI should be developed on top in order to make it easy to test as development proceeds. 

After this we should be able to fill in the missing client and blockchain logic one user-facing operation at a time. (Withdraw, Transfer, View Balance, etc.) 

Then we can move on to implementing a UI and additional asset types and transfer backends / deployment targets.

**Comment by alex-miller-0** [comment]
I agree with all of this. IMO the MVP should be a CLI that is capable of creating, loading, exchanging, and redeeming a phonon.

The exchanging part is the most complex because it involves communication between two users' terminals (more NAT traversal issues!), so I think this document/checklist also needs to mention that as part of the scope.

**Comment by maevyn11** [comment]
Much of this has been implemented and this document has outlived its usefulness. Going to close in favor of defining the remaining roadmap within the Phonon Project
